### ISSUE TITLE
Issue when downloading whole account of a lot of videos

### ISSUE THREAD

**Issue by Joshua-Noakes1** [Joshua-Noakes1/accore#39]
```nodejs
/app/node_modules/discord.js/src/util/Util.js:417
    if (!allowEmpty && data.length === 0) throw new error(errorMessage);
                                                ^
RangeError [EMBED_FIELD_VALUE]: MessageEmbed field values must be non-empty strings.
    at Function.verifyString (/app/node_modules/discord.js/src/util/Util.js:417:49)
    at Function.normalizeField (/app/node_modules/discord.js/src/structures/MessageEmbed.js:544:19)
    at /app/node_modules/discord.js/src/structures/MessageEmbed.js:565:14
    at Array.map (<anonymous>)
    at Function.normalizeFields (/app/node_modules/discord.js/src/structures/MessageEmbed.js:564:8)
    at MessageEmbed.addFields (/app/node_modules/discord.js/src/structures/MessageEmbed.js:328:42)
    at /app/lib/tiktok/videoHandle.js:173:14
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async asyncForEach (/app/lib/tiktok/videoHandle.js:235:9) {
  [Symbol(code)]: 'EMBED_FIELD_VALUE'
```

**Comment by faileador1** [comment]
Same here

```
[TikTok - Error] Failed to send embed 5 of 92
TypeError: Cannot read properties of undefined (reading 'length')
    at /app/lib/tiktok/videoHandle.js:199:48
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async asyncForEach (/app/lib/tiktok/videoHandle.js:238:9)
    at async videoHandle (/app/lib/tiktok/videoHandle.js:60:5)
    at async Command.callback [as _callback] (/app/commands/tiktok/video.js:93:9)
    at async SlashCommands.invokeCommand (/app/node_modules/wokcommands/dist/SlashCommands.js:155:23)
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at unlinkSync (node:fs:1719:10)
    at /app/lib/tiktok/videoHandle.js:227:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async asyncForEach (/app/lib/tiktok/videoHandle.js:238:9)
    at async videoHandle (/app/lib/tiktok/videoHandle.js:60:5)
    at async Command.callback [as _callback] (/app/commands/tiktok/video.js:93:9)
    at async SlashCommands.invokeCommand (/app/node_modules/wokcommands/dist/SlashCommands.js:155:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by Joshua-Noakes1** [comment]
I've been a bit busy recently but I'll have a look today to try and squash this bug!

**Comment by faileador1** [comment]
I love your dockerized discord bot, thanks for your hard work.

No problems downloading only all non-watermarked videos from random account (93 in total). I'm really not interested on GIF and watermarked videos so I have commented those lines and bot download all content with no problem.

Maybe this issue is related to GIFs or watermarked videos.

```[TikTok - Success] Successfuly send embed 93 of 93```

**Comment by faileador1** [comment]
Nevermind. Tried another account and got an error after 73 of 148.

```
/app/lib/tiktok/videoLib/extractVideoData.js:33
                watermarkedURL: video.formats[videoIndexes.watermark].url,
                                                                      ^
TypeError: Cannot read properties of undefined (reading 'url')
    at extractVideoData (/app/lib/tiktok/videoLib/extractVideoData.js:33:71)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/lib/tiktok/videoHandle.js:70:27
    at async asyncForEach (/app/lib/tiktok/videoHandle.js:241:9)
    at async videoHandle (/app/lib/tiktok/videoHandle.js:60:5)
    at async Command.callback [as _callback] (/app/commands/tiktok/video.js:93:9)
```

**Comment by Joshua-Noakes1** [comment]
Do you mind sharing the accounts which caused the crashes?

**Comment by faileador1** [comment]
> Do you mind sharing the accounts which caused the crashes?

https://www.tiktok.com/@nagoreiturregi/video/7070879067586972933

This video always gives me error

**Comment by Joshua-Noakes1** [comment]
Something is wrong on TikTok's side as in Discord the video will only play if it's downloaded and just fully refuses to play in my browser 
![image](https://user-images.githubusercontent.com/53623449/163876918-f627fcdf-0e4e-4dfb-b0b7-7e3ab58d159f.png)

**Comment by Joshua-Noakes1** [comment]
> > Do you mind sharing the accounts which caused the crashes?
> 
> https://www.tiktok.com/@nagoreiturregi/video/7070879067586972933
> 
> This video always gives me error

just pushed a fix to the dev branch which should fix this https://github.com/Joshua-Noakes1/ayanami/tree/e7d51cffe6567521fe1ed04d9cec5b5fd9a3b2f8 (image built [here](https://github.com/Joshua-Noakes1/ayanami/actions/runs/2186204027))

im still looking into the issue with mass downloading accounts

**Comment by Joshua-Noakes1** [comment]
> Same here
> 
> ```
> [TikTok - Error] Failed to send embed 5 of 92
> TypeError: Cannot read properties of undefined (reading 'length')
>     at /app/lib/tiktok/videoHandle.js:199:48
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async asyncForEach (/app/lib/tiktok/videoHandle.js:238:9)
>     at async videoHandle (/app/lib/tiktok/videoHandle.js:60:5)
>     at async Command.callback [as _callback] (/app/commands/tiktok/video.js:93:9)
>     at async SlashCommands.invokeCommand (/app/node_modules/wokcommands/dist/SlashCommands.js:155:23)
> node:internal/errors:464
>     ErrorCaptureStackTrace(err);
>     ^
> 
> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
>     at unlinkSync (node:fs:1719:10)
>     at /app/lib/tiktok/videoHandle.js:227:15
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async asyncForEach (/app/lib/tiktok/videoHandle.js:238:9)
>     at async videoHandle (/app/lib/tiktok/videoHandle.js:60:5)
>     at async Command.callback [as _callback] (/app/commands/tiktok/video.js:93:9)
>     at async SlashCommands.invokeCommand (/app/node_modules/wokcommands/dist/SlashCommands.js:155:23) {
>   code: 'ERR_INVALID_ARG_TYPE'
> }
> ```

do you have the account that caused this crash?

**Comment by faileador1** [comment]
> > > Do you mind sharing the accounts which caused the crashes?
> > 
> > 
> > https://www.tiktok.com/@nagoreiturregi/video/7070879067586972933
> > This video always gives me error
> 
> just pushed a fix to the dev branch which should fix this https://github.com/Joshua-Noakes1/ayanami/tree/e7d51cffe6567521fe1ed04d9cec5b5fd9a3b2f8 (image built [here](https://github.com/Joshua-Noakes1/ayanami/actions/runs/2186204027))
> 
> im still looking into the issue with mass downloading accounts

I'm testing dev branch and is working like a charm.

Tons of thanks.


> > Same here
> > ```
> > [TikTok - Error] Failed to send embed 5 of 92
> > TypeError: Cannot read properties of undefined (reading 'length')
> >     at /app/lib/tiktok/videoHandle.js:199:48
> >     at runMicrotasks (<anonymous>)
> >     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> >     at async asyncForEach (/app/lib/tiktok/videoHandle.js:238:9)
> >     at async videoHandle (/app/lib/tiktok/videoHandle.js:60:5)
> >     at async Command.callback [as _callback] (/app/commands/tiktok/video.js:93:9)
> >     at async SlashCommands.invokeCommand (/app/node_modules/wokcommands/dist/SlashCommands.js:155:23)
> > node:internal/errors:464
> >     ErrorCaptureStackTrace(err);
> >     ^
> > 
> > TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
> >     at unlinkSync (node:fs:1719:10)
> >     at /app/lib/tiktok/videoHandle.js:227:15
> >     at runMicrotasks (<anonymous>)
> >     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> >     at async asyncForEach (/app/lib/tiktok/videoHandle.js:238:9)
> >     at async videoHandle (/app/lib/tiktok/videoHandle.js:60:5)
> >     at async Command.callback [as _callback] (/app/commands/tiktok/video.js:93:9)
> >     at async SlashCommands.invokeCommand (/app/node_modules/wokcommands/dist/SlashCommands.js:155:23) {
> >   code: 'ERR_INVALID_ARG_TYPE'
> > }
> > ```
> 
> do you have the account that caused this crash?

@aainhoacabrera. Dev branch downloaded all that account with no problem.

**Comment by Joshua-Noakes1** [comment]
Great I'll close this issue now! Thank for your help
