### ISSUE TITLE
[Feature Request] Translate

### ISSUE THREAD

**Issue by faileador1** [Joshua-Noakes1/accore#45]
Choose media types to download from boolean environmental variables in docker compose-file.

Gifs and watermarked videos are not interesting for me and I think it could be a good feature to implement.

PS: here you have a volunteer if you want to translate it into spanish. Actually I'm the translator of Stashapp (https://translate.stashapp.cc/projects/stash/stash-desktop-client/es/#information)

**Comment by Joshua-Noakes1** [comment]
> Choose media types to download from boolean environmental variables in docker compose-file.
>
> Gifs and watermarked videos are not interested for me and I think it could be a good feature to
> implement.

I've been looking into restructuring how ayanami works so I'll definitely look into adding ways to deselect the gif / watermarked video


> PS: here you have a volunteer if you want to translate it into spanish. Actually I'm the translator of Stashapp (https://translate.stashapp.cc/projects/stash/stash-desktop-client/es/#information)

This would be great, I'll look into adding json files for translations with the embeds

**Comment by Joshua-Noakes1** [comment]
> Gifs and watermarked videos are not interesting for me and I think it could be a good feature to implement.
> 

I believe that having all possible media options to the user is the best course of action, if you would like a smaller version feel free to fork the dev-new branch once it's working again.

**Comment by Joshua-Noakes1** [comment]
> > PS: here you have a volunteer if you want to translate it into spanish. Actually I'm the translator of Stashapp (https://translate.stashapp.cc/projects/stash/stash-desktop-client/es/#information)
> 
> This would be great, I'll look into adding json files for translations with the embeds

DJS V14 supports localizations within the client, maybe not embed etc but this would make transalte work slightly easier.  https://discordjs.guide/interactions/slash-commands.html#localizations

**Comment by Joshua-Noakes1** [comment]
https://discordjs.guide/interactions/slash-commands.html#localized-responses

**Comment by Joshua-Noakes1** [comment]
https://web.archive.org/web/20220902094547/https://discordjs.guide/interactions/slash-commands.html#localizations
https://www.npmjs.com/package/linguini
https://discord.com/developers/docs/reference#locales

**Comment by Joshua-Noakes1** [comment]
Translations can now be handeled within a JSON file and work using the language which is returned with the interaction 
![image](https://user-images.githubusercontent.com/53623449/202540891-56f7af29-2ec2-4a09-b6c3-32968e74752b.png)

I'll add more to the translations as v5 is built out
