### ISSUE TITLE
[Feature Request] Skip downloaded items 

### ISSUE THREAD

**Issue by faileador1** [Joshua-Noakes1/accore#47]
For this purpose should be a database to store (at least) the video ID.

Issues: once a video is deleted from channel it could not be redownloaded.

**Comment by Joshua-Noakes1** [comment]
This would stop someone re-downloading a video if they accidently delete it or if a feature is added and they want to re-download a video to get that new feature. Feel free to make a PR if you have something that could solve that issue

**Comment by Joshua-Noakes1** [comment]
> This would stop someone re-downloading a video if they accidently delete it or if a feature is added and they want to re-download a video to get that new feature. Feel free to make a PR if you have something that could solve that issue 

Closing as not planned, over the last 3 months I've had to re-download a few videos and this feature would make it impossible.
